# Generated by Django 4.2.5 on 2025-01-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0014_alter_screening_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='histopath_details',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
