# Generated by Django 4.2.5 on 2025-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0015_patient_histopath_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
