# Generated by Django 4.2.5 on 2025-01-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0016_alter_physicalexam_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='salivary_gland_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='salivary_gland_status',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Left Obstruction', 'Left Obstruction'), ('Right Obstruction', 'Right Obstruction')], max_length=120, null=True),
        ),
    ]
