# Generated by Django 4.2.5 on 2025-01-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0017_alter_screening_salivary_gland_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bp',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='ecog_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='local_symptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pain_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='systemic_symptoms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
