# Generated by Django 4.2.5 on 2025-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0019_alter_patient_histopath_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
