# Generated by Django 4.2.5 on 2025-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0020_alter_screening_assessment_alter_screening_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
