# Generated by Django 4.2.5 on 2025-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0021_alter_physicalexam_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
