# Generated by Django 4.2.5 on 2025-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_4', '0005_alter_followup_assessment_alter_followup_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='alkaline_phosphatase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='assessment',
            field=models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Intermediate Risk', 'Intermediate Risk'), ('High Risk', 'High Risk')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='bilirubins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='fdgpetct_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='gapsma_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prostate SUV'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='hematocrit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='hemoglobin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lactate_hydrogenase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='plan',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='platelet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='psa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='rbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='sgpt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
