from .models import *
from django import forms
from django.forms import ModelChoiceField, ModelForm

# ADDING DATA
class AddFollowUp(ModelForm):
    class Meta:
        model = FollowUp
        fields = ['date_of_follow_up', 'psa', 'creatinine', 'wbc', 'rbc', 'hemoglobin', 'hematocrit', 'platelet', 'lactate_hydrogenase', 'alkaline_phosphatase', 'sgpt', 'sgot', 'bilirubins', 
        'salivary_gland_status', 'salivary_gland_image', 'bone_metastasis_status', 'bone_scan_image', 'renal_scintigraphy', 'gapsma_choices', 'gapsma_img', 
        'gapsma_prostate_lesion_status', 'gapsma_prostate_location', 'gapsma_prostate_suv', 'gapsma_prostate_size',
        'gapsma_lymph_node_lesion_status', 'gapsma_lymph_node_location', 'gapsma_lymph_node_suv', 'gapsma_lymph_node_size',
        'gapsma_bone_lesion_status', 'gapsma_bone_location', 'gapsma_bone_suv', 'gapsma_bone_size',
        'gapsma_brain_lesion_status', 'gapsma_brain_location', 'gapsma_brain_suv', 'gapsma_brain_size',
        'gapsma_lung_lesion_status', 'gapsma_lung_location', 'gapsma_lung_suv', 'gapsma_lung_size',
        'gapsma_liver_lesion_status', 'gapsma_liver_location', 'gapsma_liver_suv', 'gapsma_liver_size',
        'fdgpetct_img',
        'fdgpetct_prostate_lesion_status', 'fdgpetct_prostate_location', 'fdgpetct_prostate_suv', 'fdgpetct_prostate_size',
        'fdgpetct_lymph_node_lesion_status', 'fdgpetct_lymph_node_location', 'fdgpetct_lymph_node_suv', 'fdgpetct_lymph_node_size',
        'fdgpetct_bone_lesion_status', 'fdgpetct_bone_location', 'fdgpetct_bone_suv', 'fdgpetct_bone_size',
        'fdgpetct_brain_lesion_status', 'fdgpetct_brain_location', 'fdgpetct_brain_suv', 'fdgpetct_brain_size',
        'fdgpetct_lung_lesion_status', 'fdgpetct_lung_location', 'fdgpetct_lung_suv', 'fdgpetct_lung_size',
        'fdgpetct_liver_lesion_status', 'fdgpetct_liver_location', 'fdgpetct_liver_suv', 'fdgpetct_liver_size',
        'assessment', 'plan']

        widgets = {
            'date_of_follow_up': forms.DateInput(attrs={'type': 'date'}),
            'psa': forms.NumberInput(attrs={'step': 'any'}),
            'creatinine': forms.NumberInput(attrs={'step': 'any'}),
            'wbc': forms.NumberInput(attrs={'step': 'any'}),
            'rbc': forms.NumberInput(attrs={'step': 'any'}),
            'hemoglobin': forms.NumberInput(attrs={'step': 'any'}),
            'hematocrit': forms.NumberInput(attrs={'step': 'any'}),
            'platelet': forms.NumberInput(attrs={'step': 'any'}),
            'lactate_hydrogenase': forms.NumberInput(attrs={'step': 'any'}),
            'alkaline_phosphatase': forms.NumberInput(attrs={'step': 'any'}),
            'sgpt': forms.NumberInput(attrs={'step': 'any'}),
            'sgot': forms.NumberInput(attrs={'step': 'any'}),
            'bilirubins': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_prostate_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_prostate_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lymph_node_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lymph_node_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_bone_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_bone_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_brain_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_brain_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lung_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lung_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_liver_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_liver_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_prostate_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_prostate_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lymph_node_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lymph_node_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_bone_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_bone_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_brain_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_brain_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lung_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lung_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_liver_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_liver_size': forms.NumberInput(attrs={'step': 'any'}),
            'assessment': forms.Select(choices=FollowUp.ASSESSMENT, attrs={'required': True}),
            'plan': forms.Textarea(attrs={'required': True}),
        }
        labels = {
            'psa': 'PSA',
            'creatinine': 'Creatinine(mg/dL)',
            'wbc': 'WBC',
            'rbc' : 'RBC',
            'hemoglobin' : 'Hemogoblin(g/dL)',
            'hematocrit' : 'Hematocrit(%)',
            'platelet' : 'Platelet Count(mcL)',
            'lactate_hydrogenase' : 'Lactate Hydrogenase(units/L)',
            'alkaline_phosphatase' : 'Alkaline Phosphatase(units/L)', 
            'sgpt' : 'SGPT(units/L)', 
            'sgot' : 'SGOT(units/L)', 
            'bilirubins' : 'Bilirubins(mg/dL)',
            'salivary_gland_status': 'Salivary Gland Status',
            'salivary_gland_image': 'Salivary Gland Image',
            'bone_metastasis_status': 'Bone Metastasis Status',
            'bone_scan_image': 'Bone Scan Image',
            'renal_scintigraphy': 'Renal Scintigraphy',
            'gapsma_choices': 'GA PSMA Type',
            'gapsma_img': 'GA PSMA Image',
            'gapsma_prostate_lesion_status': 'GA PSMA Prostate Lesion Status',
            'gapsma_prostate_location': 'GA PSMA Prostate Location',
            'gapsma_prostate_suv': 'GA PSMA Prostate SUV',
            'gapsma_prostate_size': 'GA PSMA Prostate Size',
            'gapsma_lymph_node_lesion_status': 'GA PSMA Lymph Node Lesion Status',
            'gapsma_lymph_node_location': 'GA PSMA Lymph Node Location',
            'gapsma_lymph_node_suv': 'GA PSMA Lymph Node SUV',
            'gapsma_lymph_node_size': 'GA PSMA Lymph Node Size',
            'gapsma_bone_lesion_status': 'GA PSMA Bone Lesion Status',
            'gapsma_bone_location': 'GA PSMA Bone Location',
            'gapsma_bone_suv': 'GA PSMA Bone SUV',
            'gapsma_bone_size': 'GA PSMA Bone Size',
            'gapsma_brain_lesion_status': 'GA PSMA Brain Lesion Status',
            'gapsma_brain_location': 'GA PSMA Brain Location',
            'gapsma_brain_suv': 'GA PSMA Brain SUV',
            'gapsma_brain_size': 'GA PSMA Brain Size',
            'gapsma_lung_lesion_status': 'GA PSMA Lung Lesion Status',
            'gapsma_lung_location': 'GA PSMA Lung Location',
            'gapsma_lung_suv': 'GA PSMA Lung SUV',
            'gapsma_lung_size': 'GA PSMA Lung Size',
            'gapsma_liver_lesion_status': 'GA PSMA Liver Lesion Status',
            'gapsma_liver_location': 'GA PSMA Liver Location',
            'gapsma_liver_suv': 'GA PSMA Liver SUV',
            'gapsma_liver_size': 'GA PSMA Liver Size',
            'fdgpetct_img': 'FDG PET CT Image',
            'fdgpetct_prostate_lesion_status': 'FDG PET CT Prostate Lesion Status',
            'fdgpetct_prostate_location': 'FDG PET CT Prostate Location',
            'fdgpetct_prostate_suv': 'FDG PET CT Prostate SUV',
            'fdgpetct_prostate_size': 'FDG PET CT Prostate Size',
            'fdgpetct_lymph_node_lesion_status': 'FDG PET CT Lymph Node Lesion Status',
            'fdgpetct_lymph_node_location': 'FDG PET CT Lymph Node Location',
            'fdgpetct_lymph_node_suv': 'FDG PET CT Lymph Node SUV',
            'fdgpetct_lymph_node_size': 'FDG PET CT Lymph Node Size',
            'fdgpetct_bone_lesion_status': 'FDG PET CT Bone Lesion Status',
            'fdgpetct_bone_location': 'FDG PET CT Bone Location',
            'fdgpetct_bone_suv': 'FDG PET CT Bone SUV',
            'fdgpetct_bone_size': 'FDG PET CT Bone Size',
            'fdgpetct_brain_lesion_status': 'FDG PET CT Brain Lesion Status',
            'fdgpetct_brain_location': 'FDG PET CT Brain Location',
            'fdgpetct_brain_suv': 'FDG PET CT Brain SUV',
            'fdgpetct_brain_size': 'FDG PET CT Brain Size',
            'fdgpetct_lung_lesion_status': 'FDG PET CT Lung Lesion Status',
            'fdgpetct_lung_location': 'FDG PET CT Lung Location',
            'fdgpetct_lung_suv': 'FDG PET CT Lung SUV',
            'fdgpetct_lung_size': 'FDG PET CT Lung Size',
            'fdgpetct_liver_lesion_status': 'FDG PET CT Liver Lesion Status',
            'fdgpetct_liver_location': 'FDG PET CT Liver Location',
            'fdgpetct_liver_suv': 'FDG PET CT Liver SUV',
            'fdgpetct_liver_size': 'FDG PET CT Liver Size',
            'assessment': 'Assessment',
            'plan': 'Plan'
        }

class EditFollowUp(ModelForm):
    class Meta:
        model = FollowUp
        fields = ['date_of_follow_up', 'psa', 'creatinine', 'wbc', 'rbc', 'hemoglobin', 'hematocrit', 'platelet', 'lactate_hydrogenase', 'alkaline_phosphatase', 'sgpt', 'sgot', 'bilirubins', 
        'salivary_gland_status', 'salivary_gland_image', 'bone_metastasis_status', 'bone_scan_image', 'renal_scintigraphy', 'gapsma_choices', 'gapsma_img', 
        'gapsma_prostate_lesion_status', 'gapsma_prostate_location', 'gapsma_prostate_suv', 'gapsma_prostate_size',
        'gapsma_lymph_node_lesion_status', 'gapsma_lymph_node_location', 'gapsma_lymph_node_suv', 'gapsma_lymph_node_size',
        'gapsma_bone_lesion_status', 'gapsma_bone_location', 'gapsma_bone_suv', 'gapsma_bone_size',
        'gapsma_brain_lesion_status', 'gapsma_brain_location', 'gapsma_brain_suv', 'gapsma_brain_size',
        'gapsma_lung_lesion_status', 'gapsma_lung_location', 'gapsma_lung_suv', 'gapsma_lung_size',
        'gapsma_liver_lesion_status', 'gapsma_liver_location', 'gapsma_liver_suv', 'gapsma_liver_size',
        'fdgpetct_img',
        'fdgpetct_prostate_lesion_status', 'fdgpetct_prostate_location', 'fdgpetct_prostate_suv', 'fdgpetct_prostate_size',
        'fdgpetct_lymph_node_lesion_status', 'fdgpetct_lymph_node_location', 'fdgpetct_lymph_node_suv', 'fdgpetct_lymph_node_size',
        'fdgpetct_bone_lesion_status', 'fdgpetct_bone_location', 'fdgpetct_bone_suv', 'fdgpetct_bone_size',
        'fdgpetct_brain_lesion_status', 'fdgpetct_brain_location', 'fdgpetct_brain_suv', 'fdgpetct_brain_size',
        'fdgpetct_lung_lesion_status', 'fdgpetct_lung_location', 'fdgpetct_lung_suv', 'fdgpetct_lung_size',
        'fdgpetct_liver_lesion_status', 'fdgpetct_liver_location', 'fdgpetct_liver_suv', 'fdgpetct_liver_size',
        'assessment', 'plan']

        widgets = {
            'date_of_follow_up': forms.DateInput(attrs={'type': 'date'}),
            'psa': forms.NumberInput(attrs={'step': 'any'}),
            'creatinine': forms.NumberInput(attrs={'step': 'any'}),
            'wbc': forms.NumberInput(attrs={'step': 'any'}),
            'rbc': forms.NumberInput(attrs={'step': 'any'}),
            'hemoglobin': forms.NumberInput(attrs={'step': 'any'}),
            'hematocrit': forms.NumberInput(attrs={'step': 'any'}),
            'platelet': forms.NumberInput(attrs={'step': 'any'}),
            'lactate_hydrogenase': forms.NumberInput(attrs={'step': 'any'}),
            'alkaline_phosphatase': forms.NumberInput(attrs={'step': 'any'}),
            'sgpt': forms.NumberInput(attrs={'step': 'any'}),
            'sgot': forms.NumberInput(attrs={'step': 'any'}),
            'bilirubins': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_prostate_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_prostate_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lymph_node_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lymph_node_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_bone_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_bone_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_brain_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_brain_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lung_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_lung_size': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_liver_suv': forms.NumberInput(attrs={'step': 'any'}),
            'gapsma_liver_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_prostate_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_prostate_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lymph_node_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lymph_node_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_bone_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_bone_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_brain_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_brain_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lung_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_lung_size': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_liver_suv': forms.NumberInput(attrs={'step': 'any'}),
            'fdgpetct_liver_size': forms.NumberInput(attrs={'step': 'any'}),
            'assessment': forms.Select(choices=FollowUp.ASSESSMENT, attrs={'required': True}),
            'plan': forms.Textarea(attrs={'required': True}),
        }
        labels = {
            'psa': 'PSA',
            'creatinine': 'Creatinine(mg/dL)',
            'wbc': 'WBC',
            'rbc' : 'RBC',
            'hemoglobin' : 'Hemogoblin(g/dL)',
            'hematocrit' : 'Hematocrit(%)',
            'platelet' : 'Platelet Count(mcL)',
            'lactate_hydrogenase' : 'Lactate Hydrogenase(units/L)',
            'alkaline_phosphatase' : 'Alkaline Phosphatase(units/L)', 
            'sgpt' : 'SGPT(units/L)', 
            'sgot' : 'SGOT(units/L)', 
            'bilirubins' : 'Bilirubins(mg/dL)',
            'salivary_gland_status': 'Salivary Gland Status',
            'salivary_gland_image': 'Salivary Gland Image',
            'bone_metastasis_status': 'Bone Metastasis Status',
            'bone_scan_image': 'Bone Scan Image',
            'renal_scintigraphy': 'Renal Scintigraphy',
            'gapsma_choices': 'GA PSMA Type',
            'gapsma_img': 'GA PSMA Image',
            'gapsma_prostate_lesion_status': 'GA PSMA Prostate Lesion Status',
            'gapsma_prostate_location': 'GA PSMA Prostate Location',
            'gapsma_prostate_suv': 'GA PSMA Prostate SUV',
            'gapsma_prostate_size': 'GA PSMA Prostate Size',
            'gapsma_lymph_node_lesion_status': 'GA PSMA Lymph Node Lesion Status',
            'gapsma_lymph_node_location': 'GA PSMA Lymph Node Location',
            'gapsma_lymph_node_suv': 'GA PSMA Lymph Node SUV',
            'gapsma_lymph_node_size': 'GA PSMA Lymph Node Size',
            'gapsma_bone_lesion_status': 'GA PSMA Bone Lesion Status',
            'gapsma_bone_location': 'GA PSMA Bone Location',
            'gapsma_bone_suv': 'GA PSMA Bone SUV',
            'gapsma_bone_size': 'GA PSMA Bone Size',
            'gapsma_brain_lesion_status': 'GA PSMA Brain Lesion Status',
            'gapsma_brain_location': 'GA PSMA Brain Location',
            'gapsma_brain_suv': 'GA PSMA Brain SUV',
            'gapsma_brain_size': 'GA PSMA Brain Size',
            'gapsma_lung_lesion_status': 'GA PSMA Lung Lesion Status',
            'gapsma_lung_location': 'GA PSMA Lung Location',
            'gapsma_lung_suv': 'GA PSMA Lung SUV',
            'gapsma_lung_size': 'GA PSMA Lung Size',
            'gapsma_liver_lesion_status': 'GA PSMA Liver Lesion Status',
            'gapsma_liver_location': 'GA PSMA Liver Location',
            'gapsma_liver_suv': 'GA PSMA Liver SUV',
            'gapsma_liver_size': 'GA PSMA Liver Size',
            'fdgpetct_img': 'FDG PET CT Image',
            'fdgpetct_prostate_lesion_status': 'FDG PET CT Prostate Lesion Status',
            'fdgpetct_prostate_location': 'FDG PET CT Prostate Location',
            'fdgpetct_prostate_suv': 'FDG PET CT Prostate SUV',
            'fdgpetct_prostate_size': 'FDG PET CT Prostate Size',
            'fdgpetct_lymph_node_lesion_status': 'FDG PET CT Lymph Node Lesion Status',
            'fdgpetct_lymph_node_location': 'FDG PET CT Lymph Node Location',
            'fdgpetct_lymph_node_suv': 'FDG PET CT Lymph Node SUV',
            'fdgpetct_lymph_node_size': 'FDG PET CT Lymph Node Size',
            'fdgpetct_bone_lesion_status': 'FDG PET CT Bone Lesion Status',
            'fdgpetct_bone_location': 'FDG PET CT Bone Location',
            'fdgpetct_bone_suv': 'FDG PET CT Bone SUV',
            'fdgpetct_bone_size': 'FDG PET CT Bone Size',
            'fdgpetct_brain_lesion_status': 'FDG PET CT Brain Lesion Status',
            'fdgpetct_brain_location': 'FDG PET CT Brain Location',
            'fdgpetct_brain_suv': 'FDG PET CT Brain SUV',
            'fdgpetct_brain_size': 'FDG PET CT Brain Size',
            'fdgpetct_lung_lesion_status': 'FDG PET CT Lung Lesion Status',
            'fdgpetct_lung_location': 'FDG PET CT Lung Location',
            'fdgpetct_lung_suv': 'FDG PET CT Lung SUV',
            'fdgpetct_lung_size': 'FDG PET CT Lung Size',
            'fdgpetct_liver_lesion_status': 'FDG PET CT Liver Lesion Status',
            'fdgpetct_liver_location': 'FDG PET CT Liver Location',
            'fdgpetct_liver_suv': 'FDG PET CT Liver SUV',
            'fdgpetct_liver_size': 'FDG PET CT Liver Size',
            'assessment': 'Assessment',
            'plan': 'Plan'
        }