# Generated by Django 4.2.5 on 2025-01-07 05:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0004_alter_therapy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='side_effects',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fatigue', 'Fatigue'), ('Nausea or Vomiting', 'Nausea or Vomiting'), ('Dry Lips or Mouth', 'Dry Lips or Mouth'), ('Headache', 'Headache'), ('Bone Pain', 'Bone Pain')], max_length=100, null=True),
        ),
    ]
